public static class StaticMemorySlinger
{
	public static void ResetStaticMemory()
	{
		WallpaperUtils.Staged = false;
		TimeKeeper.NightmareEndingTriggered = false;
		WorldManager.DevTeleportation = false;
		HalloweenEvent.LightsLocked = false;
		EventManager.ElevatorOpened = false;
		CustomElevatorManager.Elevating = false;
		CustomElevatorManager.DOOM3D = false;
		CustomElevatorManager.KillDSAS = false;
		RareEvents.Roll();
		SpeedPoll.speedManipulatorActive = false;
		KeyPoll.keyManipulatorData = KEY_CUE_MODE.DEFAULT;
		WiFiPoll.ResetWiFiPoll();
		TheSwan.mySkyBreak = null;
		TheSwanBehaviour.SwanActivatedBefore = false;
		TheSwanBehaviour.SwanInControlOfDisco = false;
		ProductsManager.ownsWhitehatScanner = false;
		ProductsManager.ownsWhitehatRouter = false;
		ProductsManager.ownsWhitehatRemoteVPN2 = false;
		ProductsManager.ownsWhitehatRemoteVPN3 = false;
		ProductsManager.ownsWhitehatDongle2 = false;
		ProductsManager.ownsWhitehatDongle3 = false;
		ProductsManager.ownsSecCams = false;
		RemoteVPNManager.AmountOfRemoteVPNsLVL1 = 0;
		RemoteVPNManager.AmountOfRemoteVPNsLVL2 = 0;
		RemoteVPNManager.AmountOfRemoteVPNsLVL3 = 0;
		SulphurInventory.SulphurAmount = 0;
		VoIPManager.VoIPShown = false;
		TextDocManager.CustomIcon = false;
		AnnBehaviour.InstalledGamingVPN = false;
		AnnBehaviour.DoneMurderPlayer = false;
		VWipeApp.ownApp = false;
		VWipeApp.Premium = false;
		CamHookBehaviour.appLaunched = false;
		CamHookBehaviour.Interruptions = false;
		CamHookBehaviour.BoughtCameras = false;
		CamBatteryController.CamsDed = false;
		BotnetAppBehaviour.OwnsBotnet = false;
		BotnetAppBehaviour.AppIsLaunched = false;
		doorlogBehaviour.Launched = false;
		EasterEggManager.EventCompleted = false;
		EasterEggManager.EasterEggsLeft = 0;
		AppCreator.AppsCreated = false;
		BinBehaviour.BinMode = false;
		WindowBehaviour.ResetDF();
		TextDocObject.ResetImageMargin();
		HackerManager.DenialHacks = 0;
		HackerManager.HackRandom = 0;
		HackerManager.Outlaw = false;
		HackerManager.GameEnded = false;
		DOSAttack.getStaticPointes1 = 0;
		vapeAttack.getPlayerSkillPoints3 = 0;
		KAttack.IsInAttack = false;
		TutorialAnnHook.YAAIRunning = false;
		TutorialAnnHook.NextVector = 0;
		BreatherManager.InvisiblePerson = false;
		BreatherManager.BreatherCooldown = false;
		BreatherManager.SwanAdded = 0;
		CultManager.HuntingLights = false;
		CultManager.StagedEnd = false;
		HitmanLobbyComputerJump.ATApartment = false;
		DollMakerManager.lucassed = false;
		TannerManager.ForcefullyReleased = false;
		DancingTanner.dancingTanner = null;
		TannerDOSPopper.DOS = 0;
		KidnapperManager.KidnapperTime = false;
		KidnapperManager.CanDoom = false;
		KidnapperManager.LeftHiding = false;
		EXESoundPopper.PoppedSounds = 0;
		WalkingEXE.WIDE = false;
		PhoneBehaviour.DevCall = false;
		PhoneBehaviour.DevAudioClip = null;
		PhoneManager.HarbingerHappened = false;
		DeepWebRadioManager.DWRTimeStamp = 0;
		DeepWebRadioManager.DWRDizzy = false;
		DeepWebRadioManager.radio = RADIO_TYPE.NONE;
		AnnBehaviour.Claffis = false;
		AnnBehaviour.ChosenAwake = false;
		TarotCardsBehaviour.Owned = false;
		TarotManager.InDenial = false;
		TarotManager.HermitActive = false;
		TarotManager.DeafActive = false;
		TarotManager.Scripted = 0;
		TarotManager.BreatherUndertaker = false;
		TarotManager.TimeController = 30;
		TarotManager.CurSpeed = playerSpeedMode.NORMAL;
		TarotCardPullAnim.ManipulatedFortune = false;
		TarotCardPullAnim.ManipulatedCard = false;
		TarotCardPullAnim.ManipulatedID = 0;
		TarotCardsBehaviour.CantRefillNow = false;
		TarotCardsBehaviour.CardsOnTable = false;
		TarotCardPullAnim.DisableVerif();
		TarotVengeance.Clear();
		DonutTrigger.Eaten = false;
		CoffeeTime.HaveCoffee = false;
		CoffeeTime.scary = false;
	}
}
